# Generated by Django 5.0.6 on 2024-05-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=200)),
                ('universite', models.TextField()),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_fin', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
