# Generated by Django 5.0.6 on 2024-05-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_alter_resume_date_debut_alter_resume_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lien',
            field=models.URLField(default='http://example.com'),
        ),
    ]
