# Generated by Django 5.0.6 on 2024-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content1',
            field=models.TextField(default='Default content1 text'),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Default description text'),
        ),
    ]
