# Generated by Django 5.0.6 on 2024-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0006_post_content1_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(default='auteur_images/staff-1.jpg', upload_to='auteur_images/'),
        ),
    ]
