# Generated by Django 5.0.6 on 2024-06-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0008_citation_paragraph_post_paragraph2_post_paragraph3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titles',
            field=models.TextField(default='Default content1 text'),
        ),
    ]
